[project]
name = "repo-checker"
version = "0.1.0"
description = "repo-checker"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-adk>=1.19.0",
    "google-genai>=1.52.0",
    "mcp-github>=0.0.3",
]
